on:
  push:
    branches:
      - master

jobs:
  sync-branch-base:
    runs-on: ubuntu-latest
    steps:
      - uses: remarkablemark/sync-branch@v1
        with:
          base: base
          head: master

  sync-branch-squash:
    runs-on: ubuntu-latest
    steps:
      - uses: remarkablemark/sync-branch@v1
        with:
          base: squash
          merge: squash

  sync-branch-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: remarkablemark/sync-branch@v1
        with:
          base: pr
          title: Sync branch title
          body: Sync branch body

  sync-branch-token:
    runs-on: ubuntu-latest
    steps:
      - uses: remarkablemark/sync-branch@v1
        with:
          base: token
          token: ${{ secrets.GITHUB_TOKEN }}
