on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: sync-branch version
        required: true
        default: master

env:
  VERSION: ${{ inputs.version || 'v1' }}

jobs:
  sync-branch-base:
    runs-on: ubuntu-latest
    steps:
      - uses: remarkablemark/sync-branch@${{ env.VERSION }}
        with:
          base: base
          head: master

  sync-branch-squash:
    runs-on: ubuntu-latest
    steps:
      - uses: remarkablemark/sync-branch@${{ env.VERSION }}
        with:
          base: squash
          merge: squash

  sync-branch-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: remarkablemark/sync-branch@${{ env.VERSION }}
        with:
          base: pr
          title: Sync branch title
          body: Sync branch body

  sync-branch-token:
    runs-on: ubuntu-latest
    steps:
      - uses: remarkablemark/sync-branch@${{ env.VERSION }}
        with:
          base: token
          token: ${{ secrets.GITHUB_TOKEN }}
